language: node_js
node_js:
  - "12"
addons:
  chrome: stable
sudo: required
#before_install:
#  -"sudo chown root /opt/google/chrome/chrome-sandbox"
#  -"sudo chomd 4755 /opt/google/chrome/chrome-sandbox"
#script: py.test
